### ISSUE TITLE
Ability to import .csv from previously saved notes thereby effectively providing another method for backing up notes.

### ISSUE THREAD

**Issue by elwill2010** [manugarg/pagenotes-issues#9]
Respectfully request ability to import previously saved notes that are in the .csv format back into the extension. This will effectively act as another method for backing up the notes. Also request the option to have the import load and fully overwriting the existing database of notes OR the option to append the import to the existing database of notes. This feature would be extremely useful. Thanks!

**Comment by manugarg** [comment]
I'm working on adding this feature. I'll publish it in a couple of days.

**Comment by manugarg** [comment]
This is now done. Release 2.4.19 has support for importing notes from a CSV file.

**Comment by elwill2010** [comment]
Awesome! You are the best. I will try it out soon. Thanks so much!

**Comment by elwill2010** [comment]
Hi Mr. Manu, so I tried out the import feature and unfortunately it doesn't work for me. It imports 3 notes only for some reason and even they seemed kind of messed up. It requires a password or something to "decrypt" those 3 notes but I never had my notes password protected in the first place. I'm using Chrome Version 96.0.4664.45 (Official Build) (64-bit) if that matters. Not sure why it doesn't work for me but just thought I'd let you know just in case others have similar issues.

**Comment by manugarg** [comment]
That's interesting. I've tried exporting/importing notes multiple times without any problems.

Is there a possibility that your CSV file somehow got changed? Is it the original copy exported by page notes earlier? How many notes do you have? Can you share part of the CSV file? it should essentially look like the following:

```
"URL","Date","Notes"
"www.delta.com","Dec 03 2021 11:23:36","Skymiles number: 00000000 #ffn"
```

In fact, export/import didn't handle encrypted notes at all until now (added this capability in 2.5.1), so I am surprised that it's giving you an option to decrypt.

**Comment by elwill2010** [comment]
I have tried several of my "backups" that were exported straight out of the pagenotes extension in the last several months. 

None of them work even though they all appear to be in the format you specified.

Here's a sample:

"URL","Date","Notes"
"https://www.instagram.com/itsmodernmillie/","Oct 09 2021 09:21:57","itsmodernmillie IG Page

Followed Millie after watching her IG training on Youtube."

I wonder if the spaces might be the cause but that's is exactly how they exported which is because I had spaces in the notes originally. 

Not sure if that matters but just thought I'd let you know. 

The only true "error" I see is the time. 

But again, it's exactly how it exported in the first place. 

Here's a couple of screenshots to show you what I see.

![Error](https://user-images.githubusercontent.com/94743332/144682536-f60cee1c-4be1-48c8-b246-efea3f274477.png)
![Error 2](https://user-images.githubusercontent.com/94743332/144682544-15969683-ec61-42b1-87c7-076b13b6f914.png)

**Comment by manugarg** [comment]
Newline in CSV fields must be doing this. I'll take a look at how we can fix this. Thanks for sharing this.

**Comment by manugarg** [comment]
I just published a new release. That should fix the problem with parsing the newline.

**Comment by elwill2010** [comment]
I updated the extension and now while it is better - because it imports all of the notes now - unfortunately they are still showing up as being encrypted just like the examples above. And it also still shows the problem with the date and time being messed up just like in the screenshots above as well.

**Comment by manugarg** [comment]
I found the bug. I'll upload the fixed version shortly.

Thanks for testing, @elwill2010! This is super helpful.

**Comment by manugarg** [comment]
2.5.3 version will fix it. It will take a few minutes to publish though.

**Comment by manugarg** [comment]
It just got published. You should be able to upgrade to 2.5.3 now.

**Comment by elwill2010** [comment]
Yes, it works now! So amazing. Thank you so much Mr. Manu!

**Comment by manugarg** [comment]
Great. Thanks for your patience and continuous feedback!
